# Platform Adaptation Tasks - All run in parallel via hierarchical process

adapt_instagram_task:
  description: >
    Adapt the edited content for Instagram, creating an engaging post that resonates with {target_audience} 
    on this visual platform. Maintain {brand_tone} tone while optimizing for Instagram's format and 
    engagement patterns.
    
    Create Instagram content with:
    1. Compelling caption (2200 characters max)
    2. Visual content description or concept
    3. Strategic hashtag selection (20-30 hashtags)
    4. Engaging opening hook
    5. Story elements and personality
    6. Clear call-to-action: {call_to_action}
    7. Line breaks for readability
    8. Emoji usage for visual appeal
    
    Focus on visual storytelling and community engagement while covering '{topic}'.
  expected_output: >
    Instagram-optimized content including:
    - Engaging caption about '{topic}' (under 2200 characters)
    - Visual content concept or description
    - 20-30 relevant and trending hashtags
    - Strong opening hook and story elements
    - {brand_tone} tone with personality
    - Clear call-to-action: {call_to_action}
    - Proper formatting with line breaks and emojis
  agent: instagram_adapter

adapt_linkedin_task:
  description: >
    Transform the edited content for LinkedIn's professional audience. Create content about '{topic}' 
    that positions expertise and provides value to {target_audience} in a professional context using 
    {brand_tone} tone.
    
    Develop LinkedIn content featuring:
    1. Professional opening that establishes credibility
    2. Industry insights and expertise demonstration
    3. Business value and practical applications
    4. Professional storytelling elements
    5. Thought leadership positioning
    6. Clear call-to-action: {call_to_action}
    7. 3-5 relevant professional hashtags
    8. Networking and engagement elements
    
    Focus on networking, expertise, and professional value related to '{topic}'.
  expected_output: >
    LinkedIn-optimized professional content including:
    - Credibility-building opening about '{topic}'
    - Industry insights and expertise demonstration
    - Business value propositions for {target_audience}
    - Professional storytelling and thought leadership
    - {brand_tone} tone adapted for professional context
    - Strategic call-to-action: {call_to_action}
    - 3-5 relevant professional hashtags
  agent: linkedin_adapter

adapt_twitter_task:
  description: >
    Create Twitter-optimized content about '{topic}' that engages {target_audience} within the platform's 
    character constraints. Maintain {brand_tone} tone while maximizing impact and shareability.
    
    Develop Twitter content with:
    1. Concise, impactful messaging (280 characters max)
    2. Strong hook or attention-grabber
    3. Key insight or value proposition
    4. 1-3 relevant hashtags
    5. Conversation-starting elements
    6. Clear call-to-action: {call_to_action}
    7. Thread potential if needed
    8. Retweet-worthy format
    
    Focus on engagement, shareability, and conversation around '{topic}'.
  expected_output: >
    Twitter-optimized content including:
    - Impactful tweet about '{topic}' (under 280 characters)
    - Strong attention-grabbing opening
    - Key insight or value for {target_audience}
    - 1-3 strategic hashtags
    - {brand_tone} tone in concise format
    - Engaging call-to-action: {call_to_action}
    - Thread expansion ideas if applicable
  agent: twitter_adapter

adapt_facebook_task:
  description: >
    Adapt the edited content for Facebook's community-focused environment. Create content about '{topic}' 
    that encourages discussion and engagement among {target_audience} while maintaining {brand_tone} tone.
    
    Create Facebook content featuring:
    1. Community-engaging opening
    2. Discussion-prompting elements
    3. Relatable storytelling
    4. Questions to encourage comments
    5. Share-worthy value proposition
    6. Clear call-to-action: {call_to_action}
    7. Optimal length for feed engagement
    8. Community-building elements
    
    Focus on community building and conversation around '{topic}'.
  expected_output: >
    Facebook-optimized community content including:
    - Engaging community-focused post about '{topic}'
    - Discussion-prompting questions and elements
    - Relatable storytelling for {target_audience}
    - {brand_tone} tone with conversational elements
    - Share-worthy insights and value
    - Community-building call-to-action: {call_to_action}
    - Optimal formatting for Facebook engagement
  agent: facebook_adapter

finalize_blog_task:
  description: >
    Format the SEO-optimized content into a complete, publication-ready blog post about '{topic}'. 
    Ensure proper structure, formatting, and final polish for {target_audience} while maintaining 
    {brand_tone} tone.
    
    Finalize blog post with:
    1. Final title and meta description
    2. Proper header structure (H1, H2, H3)
    3. Introduction, body, and conclusion formatting
    4. Call-to-action placement: {call_to_action}
    5. Author bio or byline suggestions
    6. Publication-ready formatting
    7. Final proofread and polish
    8. SEO elements integration
    
    Ensure the blog post is complete and ready for immediate publication.
  expected_output: >
    Complete, publication-ready blog post including:
    - Final optimized title and meta description
    - Properly structured content with headers (H1, H2, H3)
    - Well-formatted introduction, body, and conclusion
    - Strategic placement of call-to-action: {call_to_action}
    - Professional formatting and layout
    - {brand_tone} tone throughout
    - SEO optimization maintained
    - Ready for immediate publication about '{topic}'
  agent: blog_adapter